`timescale 1ns/1ps
// TESTBED.v  -  Simulation testbench for Interpolator
//
// x1[m] = cos(2*pi*(m/10+0.5)) + j*sin(...)   phi=1
// IntpIn updates every 8 negedge-clk cycles (m = 10..22)
// mu cycles 0, 1/8, ..., 7/8 every negedge-clk
// All inputs change AT negedge clk
//
// Expected output values generated by MATLAB step4_bf16_compare.m

module TESTBED;

// =========================================================
// Signals
// =========================================================
reg         clk;
reg         rst_n;
reg  [31:0] IntpIn;
reg  [15:0] mu;
wire [31:0] IntpOut;

// =========================================================
// DUT
// =========================================================
Interpolator dut (
    .clk    (clk),
    .rst_n  (rst_n),
    .IntpIn (IntpIn),
    .mu     (mu),
    .IntpOut(IntpOut)
);

// =========================================================
// Clock: 10 ns period (100 MHz)
// =========================================================
initial clk = 1'b1;
always  #5 clk = ~clk;

// =========================================================
// BF16 constants
// =========================================================
// mu values: 0, 1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8
reg [15:0] mu_tbl [0:7];
initial begin
    mu_tbl[0] = 16'h0000; // 0
    mu_tbl[1] = 16'h3E00; // 0.125
    mu_tbl[2] = 16'h3E80; // 0.25
    mu_tbl[3] = 16'h3EC0; // 0.375
    mu_tbl[4] = 16'h3F00; // 0.5
    mu_tbl[5] = 16'h3F20; // 0.625
    mu_tbl[6] = 16'h3F40; // 0.75
    mu_tbl[7] = 16'h3F60; // 0.875
end

// IntpIn: x1[m] BF16 {re[15:0], im[15:0]}, m = 10..22  (13 entries)
// Generated by MATLAB step4_bf16_compare.m -> 00_TESTBED/src/IntpIn.dat
reg [31:0] IntpIn_tbl [0:12];
initial $readmemh("C:/Project/DSP in VLSI/Lab3_Interpolator/00_TESTBED/src/IntpIn.dat", IntpIn_tbl);

// Expected outputs: out_bf16(m,mu), m=10..20, mu=0..7/8  (88 entries)
// index = (m-10)*8 + mu_i  (mu_i = 0..7)
// Generated by MATLAB step4_bf16_compare.m -> 00_TESTBED/src/exp_out.dat
reg [31:0] exp_tbl [0:87];
initial $readmemh("C:/Project/DSP in VLSI/Lab3_Interpolator/00_TESTBED/src/exp_out.dat", exp_tbl);

// =========================================================
// Stimulus
// =========================================================
integer     m_idx;
integer     i;

initial begin
    // -- Initialize --
    rst_n  = 1'b1;
    IntpIn = 32'd0;
    mu     = 16'd0;

    // -- 100 ns initial delay --
    #100;

    // -- Assert reset --
    rst_n = 1'b0;
    @(negedge clk);
    @(negedge clk);
    rst_n = 1'b1;

    // -- Drive inputs for m=10..22 (13 IntpIn values) --
    // IntpIn changes every 8 negedge-clk; mu changes every negedge-clk.
    // Total: 13 * 8 = 104 cycles (shift register fills after 3*8=24 cycles).
    for (m_idx = 0; m_idx < 13; m_idx = m_idx + 1) begin
        @(negedge clk);
        IntpIn = IntpIn_tbl[m_idx];
        for (i = 0; i < 8; i = i + 1) begin
            mu = mu_tbl[i];            // i already cycles 0..7
            if (i < 7) @(negedge clk);
        end
    end

    // -- Extra cycles to flush pipeline --
    repeat (4) @(negedge clk);

    // Verification is done via waveform inspection:
    //   compare IntpOut against exp_tbl entries loaded from exp_out.dat.
    // Due to the 3-cycle shift-register fill and mu-phase offset, outputs
    // do not appear in sequential exp_tbl order; use waveform viewer to
    // cross-check the 88 valid outputs (m=10..20, mu=0..7/8).
    $display("=== Simulation done. Check waveform for IntpOut. ===");

    #50;
    $finish;
end

// =========================================================
// Waveform dump
// =========================================================
initial begin
    $dumpfile("interpolator.vcd");
    $dumpvars(0, TESTBED);
end

// =========================================================
// Monitor: print every output for inspection
// =========================================================
always @(negedge clk) begin
    $display("t=%0t  mu=%04h  IntpIn=%08h  IntpOut=%08h",
             $time, mu, IntpIn, IntpOut);
end

endmodule
